#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Running build before commit..."
npm run build

# Check if the build was successful
if [ $? -eq 0 ]; then
    echo "Build successful, proceeding with commit"
    exit 0
else
    echo "Build failed, commit aborted"
    exit 1
fi
